# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=50, verbose_name='Purchaser name')),
                ('item_description', models.CharField(max_length=50, verbose_name='Item description')),
                ('item_price', models.FloatField(verbose_name='Item price')),
                ('purchase_count', models.IntegerField(verbose_name='Purcharse count')),
                ('merchant_address', models.CharField(max_length=50, verbose_name='Merchart address')),
                ('merchant_name', models.CharField(max_length=50, verbose_name='Nerchant name')),
            ],
        ),
    ]
