# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20161207_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parse_complete',
            field=models.NullBooleanField(default=False),
        ),
    ]
